eureka:
  client:
    serviceUrl:
      defaultZone: http://10.201.61.10:8761/eureka/
    healthcheck:
      enabled: true  
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
management:
 endpoints:
  web:
   exposure:
    include: hystrix.stream
